
Neos:
  Flow:
    i18n:
      defaultLocale: ru
  ContentRepository:
    contentDimensions:
      language:
        label: Languages
        icon: icon-language
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: ru
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: ru
        presets:
          # de:
          #   label: Deutsch
          #   values:
          #     - de
          #   uriSegment: 'de'
          ru:
            label: Russian
            values:
              - ru
            uriSegment: ''
  Neos:
    userInterface:
      defaultLanguage: ru
      translation:
        autoInclude:
          Codermen.Testsite:
            - Main
            - 'NodeTypes/*'
